language: java


before_script:
  - echo "Build started"
script:
  - mvn package
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
after_failure:
  - echo "Build was failed"