language: java

before_script:
  - echo "Build started"
script:
  script: mvn package -DskipTests
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - echo "Build was failed"